apiVersion: v1
kind: Pod
metadata:
  name: live-configmap-pod
spec:
  containers:
  - name: busybox-live-pod
    image: busybox:latest
    command:
    - sh
    - -c
    - |
      while true
      do
        echo "Message: $(cat /config/message)"
        sleep 5
      done

    volumeMounts:
    - name: configmap-volume
      mountPath: /config

  volumes:
  - name: configmap-volume
    configMap:
      name: live-config
